[build]
  publish = "build"  # Adjust this if your build directory is different, e.g., "dist" or "public"
  command = "npm run build"  # or the build command for your React project

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
